### PR TITLE
Always know your rate limits

### PR DESCRIPTION
**Pull request by vrudikov**
Sometimes we should know rate limits forecast in successful response or even for failure. It will give us possibility to choose our request strategy

### CODE REVIEW

**Comment by ParisMi** [comment]
Hey @vrudikov, thanks for submitting this and sorry for the delay.

This approach definitely seems to work, and I appreciate the thoroughness of the change (including tests!).

However, I feel the approach could be more general and the duplication of the "extract rate limits from headers and store them" in both the RequestExecutorHandler and the FCRetrofitCallback could be improved.

I have an alternative implementation that has practically the exact same API here: https://github.com/fullcontact/fullcontact4j/pull/31 

let me know if that one works for you instead.

Thanks again for submitting this!

**Comment by vrudikov** [comment]
Hi @ParisMi. Awesome. Will review your changes now

**Comment by vrudikov** [comment]
@ParisMi Should i decline this PR? or close it?

**Comment by ParisMi** [comment]
yeah, addressed by https://github.com/fullcontact/fullcontact4j/pull/31. Thanks again @vrudikov !

**Comment by vrudikov** [comment]
@ParisMi Thank you for official support. Seeya

**Pull request closed without merging**
