### PR TITLE
Gradle build

### PR DESCRIPTION
**Pull request by ryanwalker**
Still need auth setup from CD/SRE team for this to actually deploy.

### CODE REVIEW

**Comment by Xorlev** [comment]
Hi @ryanwalker, I think you meant for this PR to be to Infusionsoft's internal fork.

**Comment by ryanwalker** [comment]
Oops, yes 😅

**Comment by Xorlev** [comment]
No worries. Let us know if we can help at all. We'd also be pleased with any improvements ya'll would like to contribute back to fullcontact4j.

**Comment by ryanwalker** [comment]
We're still having a problem using the sdk on GAE standard environment. We tried passing in google's ThreadManager.currentRequestThreadFactory() into the sdk, but we get a thread group exception. We are attempting to resolve it by forking and trying to use this client `UrlFetchClient`.
WE aren't able to pass this into a constructor. We're changing the constructor to make it work for us.

**Comment by dkpalmer** [comment]
Stack trace:

```
Exception in thread "Thread-9" java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
	at java.security.AccessController.checkPermission(AccessController.java:559)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Factory$CustomSecurityManager.checkPermission(DevAppServer2Factory.java:232)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Factory$CustomSecurityManager.checkAccess(DevAppServer2Factory.java:257)
	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
	at java.lang.Thread.init(Thread.java:391)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:548)
	at retrofit.Platform$Base$2.newThread(Platform.java:91)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:610)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:924)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1371)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:276)
	at com.sun.proxy.$Proxy56.uploadCard(Unknown Source)
	at com.fullcontact.api.libs.fullcontact4j.http.cardreader.CardReaderUploadRequest.makeRequest(CardReaderUploadRequest.java:33)
	at com.fullcontact.api.libs.fullcontact4j.http.RequestExecutorHandler$1.run(RequestExecutorHandler.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.google.appengine.tools.development.BackgroundThreadFactory$1$1.run(BackgroundThreadFactory.java:60)
```

Yes, `UrlFetchClient` is specific to GAE. It worked for us as the client for RestAdapter in our own Retrofit code.

I think the hiccup we're running into with GAE is per the following in their documentation at https://cloud.google.com/appengine/docs/standard/java/runtime:

> However, you must use one of the methods on `ThreadManager` to create your threads. You cannot invoke new Thread() yourself or use the default thread factory.

I'm going to try and see if I can provide a custom `ThreadFactory` and create threads using their `ThreadManager`. I'll report back.

**Comment by dkpalmer** [comment]
When I try to provide a custom `ThreadFactory` that creates threads via GAE's `ThreadManager`, I still see a "modifyThreadGroup" exception (same as above) and the app ends up hanging. I'm guessing threads may be getting created somewhere else?

I'm trying to hack `UrlFetchClient` in now to see if things will work. If support in fc4j was there that would be 👍 .

**Comment by ParisMi** [comment]
```
at retrofit.Platform$Base$2.newThread(Platform.java:91)
```
is pointing at 
````
        Executor defaultHttpExecutor() {
            return Executors.newCachedThreadPool(new ThreadFactory() {
                public Thread newThread(final Runnable r) {
                    return new Thread(new Runnable() {
                        public void run() {
                            Thread.currentThread().setPriority(1);
                            r.run();
                        }
                    }, "Retrofit-Idle");
                }
            });
        }
```
looks like there's another executor that snuck intro retrofit. We could add the ability to specify the executor there, too -- I _think_ that'll be all the places where `new Thread()` eventually gets called.

**Comment by ParisMi** [comment]
I'll add this to the to-do list.

**Comment by ParisMi** [comment]
@dkpalmer https://github.com/fullcontact/fullcontact4j/pull/46 (5.3.0) supports specifying the `httpExecutor`. hopefully that's the last one.

**Comment by dkpalmer** [comment]
@ParisMi Unfortunately, 5.3.0 resulted in a new modifyThread permission issue:

```
Exception in thread "Thread-9" java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThread")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
	at java.security.AccessController.checkPermission(AccessController.java:559)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Factory$CustomSecurityManager.checkPermission(DevAppServer2Factory.java:232)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Factory$CustomSecurityManager.checkAccess(DevAppServer2Factory.java:269)
	at java.lang.Thread.checkAccess(Thread.java:1419)
	at java.lang.Thread.setName(Thread.java:1160)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:398)
	at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
	at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
	at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.google.appengine.tools.development.BackgroundThreadFactory$1$1.run(BackgroundThreadFactory.java:60)
```

On another note, I hacked a `UrlFetchClient` into our fork of your lib and was able to get cards to upload locally. When I deployed to GAE's sandbox environment, I was met with an exception about a class (`ProxySelector`) not being on their whitelist. I followed up by rolling it back from OkHttp3 to OkHttp2 and seemed to get around the whitelist issue.

We greatly appreciate the support you guys have provided as well as the quick turnarounds. Unfortunately it appears GAE is the gift that keeps on giving. Based on what I hacked into our fork, the only combination of things that has seemed to work has been OkHttp2 + support for `UrlFetchClient`.

**Pull request closed without merging**
